spring.application.name=MiniUSOS

spring.datasource.url=jdbc:postgresql://localhost:5432/miniusos_db
spring.datasource.username=usos_admin
spring.datasource.password=superhaslo

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration