-- init schema
CREATE TABLE course
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    ects_points INTEGER                                 NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE enrollment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id      BIGINT,
    course_id       BIGINT,
    enrollment_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_enrollment PRIMARY KEY (id)
);

CREATE TABLE grade
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id   BIGINT,
    student_id  BIGINT,
    score       INTEGER                                 NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_grade PRIMARY KEY (id)
);

CREATE TABLE student
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    index_number VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE course
    ADD CONSTRAINT uc_course_name UNIQUE (name);

ALTER TABLE student
    ADD CONSTRAINT uc_student_indexnumber UNIQUE (index_number);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE;

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE;