ALTER TABLE enrollment
    DROP CONSTRAINT fk_enrollment_on_course;

ALTER TABLE grade
    DROP CONSTRAINT fk_grade_on_course;

CREATE TABLE course_detail
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    ects_points INTEGER                                 NOT NULL,
    CONSTRAINT pk_coursedetail PRIMARY KEY (id)
);

CREATE TABLE course_schedule
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id  BIGINT,
    date       date,
    start_time time WITHOUT TIME ZONE,
    end_time   time WITHOUT TIME ZONE,
    CONSTRAINT pk_courseschedule PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE employee_course_detail
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id      BIGINT,
    course_detail_id BIGINT,
    CONSTRAINT pk_employeecoursedetail PRIMARY KEY (id)
);

CREATE TABLE major
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_major PRIMARY KEY (id)
);

CREATE TABLE major_detail
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    major_id      BIGINT,
    academic_year INTEGER,
    CONSTRAINT pk_majordetail PRIMARY KEY (id)
);

CREATE TABLE student_group
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_course_detail_id BIGINT,
    group_number              INTEGER,
    CONSTRAINT pk_studentgroup PRIMARY KEY (id)
);

CREATE TABLE student_group_assignment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id       BIGINT,
    student_group_id BIGINT,
    CONSTRAINT pk_studentgroupassignment PRIMARY KEY (id)
);

ALTER TABLE course
    ADD course_detail_id BIGINT;

ALTER TABLE course
    ADD course_type VARCHAR(255);

ALTER TABLE course
    ADD hours INTEGER;

ALTER TABLE course_detail
    ADD CONSTRAINT uc_coursedetail_name UNIQUE (name);

ALTER TABLE course_schedule
    ADD CONSTRAINT FK_COURSESCHEDULE_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE course
    ADD CONSTRAINT FK_COURSE_ON_COURSEDETAIL FOREIGN KEY (course_detail_id) REFERENCES course_detail (id);

ALTER TABLE employee_course_detail
    ADD CONSTRAINT FK_EMPLOYEECOURSEDETAIL_ON_COURSEDETAIL FOREIGN KEY (course_detail_id) REFERENCES course_detail (id);

ALTER TABLE employee_course_detail
    ADD CONSTRAINT FK_EMPLOYEECOURSEDETAIL_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course_detail (id);

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_COURSE FOREIGN KEY (course_id) REFERENCES course_detail (id);

ALTER TABLE major_detail
    ADD CONSTRAINT FK_MAJORDETAIL_ON_MAJOR FOREIGN KEY (major_id) REFERENCES major (id);

ALTER TABLE student_group_assignment
    ADD CONSTRAINT FK_STUDENTGROUPASSIGNMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student_group_assignment
    ADD CONSTRAINT FK_STUDENTGROUPASSIGNMENT_ON_STUDENTGROUP FOREIGN KEY (student_group_id) REFERENCES student_group (id);

ALTER TABLE student_group
    ADD CONSTRAINT FK_STUDENTGROUP_ON_EMPLOYEECOURSEDETAIL FOREIGN KEY (employee_course_detail_id) REFERENCES employee_course_detail (id);

ALTER TABLE course
    DROP COLUMN ects_points;

ALTER TABLE course
    DROP COLUMN name;